### ISSUE TITLE
Convert all XML elements into JSON

### ISSUE THREAD

**Issue by cgi1** [csaf-tools/CVRF-CSAF-Converter#10]
After having a code basis for flat (#3) and recursive (#9) conversion, we now have the basis to basically convert all elements of the XML tree into JSON.

Elements (Pre #6)
- [x] Leaf Elements of the document root (DocumentTitle DONE, DocumentType -> category (#13), DocumentDistribution OPEN, AggregateSeverity (#39))
- [x] DocumentPublisher (#3)
- [x] DocumentTracking (#9)
- [x] DocumentNotes (#35)
- [x] DocumentReferences (#28)
- [x] Acknowledgments (#29)
- [x] ProductTree (#26)
- [x] Vulnerability (#30)

**Comment by cgi1** [comment]
This issue becomes an EPIC, where @sustefil will split up the different XML elements (1st hierachie) into smaller issues.

**Comment by sustefil** [comment]
Created a check-box list for the Sections. Each entry should have its corresponding issue, as it's now.

Vulnerability section is bigger, will be probably split into smaller issues when we are on it

**Comment by cgi1** [comment]
DONE HERE 🥳 🎉 

Thank you @zpevma and @sustefil for doing the overwhelming amount of implementation work! 🙏 
Also, the reviews by @sthagen and @tschmidtb51 greatly enhanced the code quality and made us write better code at all. 👨‍💻
