### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-tools/CVRF-CSAF-Converter#106]
Please transfer the ownership of the organization an the repo to BSI members.

**Comment by tschmidtb51** [comment]
Flagging @pixelkunst-net for attention.

**Comment by cgi1** [comment]
Turned @tschmidtb51 and @mfd2007 into Admin. Downgraded all others to Maintainer.

**Comment by tschmidtb51** [comment]
@cgi1 Thanks. Please also make @tschmidtb51 and @mfd2007 to owners of the organization (csaf-tools).

**Comment by cgi1** [comment]
done.
