### ISSUE TITLE
Version 1.0.0 released

### ISSUE THREAD

**Issue by sustefil** [csaf-tools/CVRF-CSAF-Converter#107]
Hi @tschmidtb51 ,

released the version 1.0.0 here and on PyPI:

https://github.com/csaf-tools/CVRF-CSAF-Converter/releases/tag/1.0.0

https://pypi.org/project/cvrf2csaf/

Please review and close

**Comment by tschmidtb51** [comment]
1.0.0 corrects defects as expected.

**Note:** Due to the delay with #106, we couldn't accept earlier.
