### ISSUE TITLE
CVRF 1.1 support

### ISSUE THREAD

**Issue by ir-dev** [csaf-tools/CVRF-CSAF-Converter#110]
Are there any intentions or reasons against designing the tool also for the conversion of CVRF 1.1 files?

In my opinion, the differences between CVRF 1.1 and 1.2 are not that big, so one could consider both versions to get a full-fledged CVRF CSAF converter.

**Comment by tschmidtb51** [comment]
Generally, no. It was just not in the scope of the project.

However, I would like to get #109 solved before looking into CVRF 1.1...

**Comment by tschmidtb51** [comment]
However, if that is relevant for you - feel free to submit a PR...

**Comment by ir-dev** [comment]
> However, if that is relevant for you - feel free to submit a PR...

Since new advisories are probably no longer issued in CVRF 1.1 and there is apparently only a small stock of old CVRF 1.1, it is not worthwhile for me, and probably not for most others either, to implement it.
