### ISSUE TITLE
Validate mandatory tests

### ISSUE THREAD

**Issue by cgi1** [csaf-tools/CVRF-CSAF-Converter#14]
Pre: #10 

Please also add CLI arg to skip mandatory tests, because the user could also fix the input in Secvisogram.

[Desc](https://docs.oasis-open.org/csaf/csaf/v2.0/csd01/csaf-v2.0-csd01.html#61-mandatory-tests)

Only the relevant parts are written in the specification, the [full examples](https://github.com/oasis-tcs/csaf/tree/master/csaf_2.0/test/validator/data/mandatory) are written here. They are failing (at least) for the specific cases. 

The naming of the examples is encoded like this:

OASIS_CSAF_TC-CSAF_2_0-2021-**6-1-05**-01.json

6.1.05 here means, that this is a test file for [Mandatory test 6.1.5](https://docs.oasis-open.org/csaf/csaf/v2.0/csd01/csaf-v2.0-csd01.html#61-mandatory-tests)

--> All mandatory tests have already been implemented by [secvisogram](https://github.com/secvisogram/secvisogram) already. More detailed [here](https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/shared/Core/entities/DocumentEntity.js#L383)

**Comment by cgi1** [comment]
@tschmidtb51: We understand, that it will be perfect to execute the mandatory tests - implemented in  secvisogram  - as part of the Github Actions chain. 

Are you aware on how to call the validation functions from the CLI? Then we will start with implementing it into Github Actions to be compliant with the mandatory tests right from the start.

Furthermore, can we assume that [secvisogram is completly validating all mandatory tests here?](https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/shared/Core/entities/DocumentEntity.js#L383)

**Comment by tschmidtb51** [comment]
> @tschmidtb51: We understand, that it will be perfect to execute the mandatory tests - implemented in secvisogram - as part of the Github Actions chain.

The [standard](https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html#915-conformance-clause-5-cvrf-csaf-converter) requires that a CVRF CSAF converter satisfies the "CSAF producer" conformance profile. The [CSAF producer](https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html#912-conformance-clause-2-csaf-producer) produces output in the CSAF format, according to the conformance profile "CSAF document" which states that a [CSAF document](https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html#911-conformance-clause-1-csaf-document) does not fail any mandatory test defined in [section 6.1](https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html#61-mandatory-tests). Therefore, the CVRF CSAF converter SHALL check (as the last step) whether the generated CSAF output is a valid CSAF document. The tests have been implemented in Secvisogram. However, just running them as GH-Actions would not be enough as the mandatory test should be an part of the CVRF CSAF converter.

> 
> Are you aware on how to call the validation functions from the CLI? Then we will start with implementing it into Github Actions to be compliant with the mandatory tests right from the start.

Unfortunately, not. I think that is not implemented at the moment.
> 
> Furthermore, can we assume that [secvisogram is completly validating all mandatory tests here?](https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/shared/Core/entities/DocumentEntity.js#L383)

No. Not all test have been implemented yet. Watch secvisogram/secvisogram#36: Once it closes all test have been implemented. The entry point is [here](https://github.com/secvisogram/secvisogram/blob/69bfe1a4a5ba54dc8503bda142cc7a70c20301ce/app/lib/shared/Core/entities/DocumentEntity.js#L402) - some tests are already extracted into [separate files](https://github.com/secvisogram/secvisogram/tree/main/app/lib/shared/Core/entities/DocumentEntity).

**Comment by tschmidtb51** [comment]
Maybe existing projects, like [sthagen/csaf-lint](https://github.com/sthagen/csaf-lint) could help in the implementation?

Flagging @sthagen for attention.

**Comment by cgi1** [comment]
Thank you for the explenation @tschmidtb51!

So of course it would be great to use a common libary in order to execute the mandatory tests in both cases - Continous Testing as part of Github Actions as well as on the converted file into JSON as part of `cvrf2csaf.py`. For further maintainance aspects, I would also suggest to not re-implement all the mandatory checks at different places.

From the code I see, that [sthagen/csaf-lint](https://github.com/sthagen/csaf-lint) already comes with [XML](https://github.com/sthagen/csaf-lint/blob/default/csaf_lint/lint.py#L176) and [JSON schema validation](https://github.com/sthagen/csaf-lint/blob/default/csaf_lint/lint.py#L153).

Invoking [csaf-lint](https://github.com/sthagen/csaf-lint) would therefore very much fullfill this requirement.

Sadly, I did not found any Validation Test implementations in [sthagen/csaf-lint](https://github.com/sthagen/csaf-lint), which checks the [Mandatory Tests](https://docs.oasis-open.org/csaf/csaf/v2.0/csd01/csaf-v2.0-csd01.html#61-mandatory-tests).

 
The question arises at this point, if we should invoke calling [the JS secvisogram checks here*](https://github.com/secvisogram/secvisogram/blob/69bfe1a4a5ba54dc8503bda142cc7a70c20301ce/app/lib/shared/Core/entities/DocumentEntity.js#L402), or if there will be a native python implementation of the checks (e.g. in csaf-lint or another project)? 

*(e.g. using [Js2Py](https://github.com/PiotrDabkowski/Js2Py). But this can cause code translating issues, so if available, we would prefer a python implementation.

**Comment by sustefil** [comment]
> Luckily, I might provide the mandatory "business level" tests within short notice as a native python implementation.

Hi @sthagen , any luck with the mandatory tests implementation?

**Comment by sthagen** [comment]
@sustefil, @tschmidtb51 ... my promise is still not broken :wink:

**Comment by cgi1** [comment]
There is a new project by @sthagen which targets mandatory tests in python: [turvallisuusneuvonta](https://github.com/sthagen/turvallisuusneuvonta)

Right now, only part of the mandatory tests are implemented yet.

We agreed with @tschmidtb51, that for now, we will integrate the execution of these tests into `cvrf2csaf.py`.
