### ISSUE TITLE
Discuss: Input validation of XML file

### ISSUE THREAD

**Issue by cgi1** [csaf-tools/CVRF-CSAF-Converter#17]
While this is not part of the offer, we would like to also run some basic input validation on XML level. 

Are you aware of a good tool to run? 

Or should we go into validating the XML schema of CVRF 1.2 (e.g. using [lxml](https://lxml.de/validation.html))?

In the end, the XML schema validator will help us to reject invalid files as a pre-step.

**Comment by tschmidtb51** [comment]
I'm currently not aware of a good tool to run. However, I think validating the input against the [XML Schemas of CSAF CVRF 1.2](https://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/) might be a good start.

**Comment by tschmidtb51** [comment]
Maybe @sthagen has additional insights.

**Comment by tschmidtb51** [comment]
Maybe existing projects, like [sthagen/csaf-lint](https://github.com/sthagen/csaf-lint) could help in the implementation?

Flagging @sthagen for attention.

**Comment by cgi1** [comment]
I will open a new ticket in csaf-lint project with more details.

**Comment by cgi1** [comment]
Waiting for @zpevma to come back from vacation - Will be opened after next internal meeting.

**Comment by zpevma** [comment]
Currently input validation is done by xsd schema.

**Comment by cgi1** [comment]
[sthagen/csaf-lint](https://github.com/sthagen/csaf-lint) is discontinued. The only option left is validating the XSD schema (which we are doing already).
