### ISSUE TITLE
Agree on logging semantics

### ISSUE THREAD

**Issue by sustefil** [csaf-tools/CVRF-CSAF-Converter#24]
Just to have a clear logging scheme, I propose these log-level meanings:

- **Critical** - Converter encountered a case which it can not handle and exits immediately without producing any output, exiting with non-zero code. E.g. invalid input CVRF
- **Error** - TBD
- **Warning** - Any intervention from the Converter which alters the output (e.g. reindexing versions to Integer)
- **Info** - Just messages about the progress (e.g. "Section Document Tracking handled successfully")

@tschmidtb51  would you agree? Do you have an idea for use-case for Errors?

**Comment by sthagen** [comment]
Not having any stakes in this, but my feedback would be:

1. I rarely see convincing separation between ERROR and CRITICAL in practical applications.
2. CSAF as trying to enforce minimum consistency to ease automated processing is a bad target for ERRORs that are not failing the conversion ...

So, I would instead plan for:

* **Error** - Converter encountered a case which it can not handle and exits immediately without producing any output, exiting with non-zero code. E.g. invalid input CVRF
* **Warning** - Any intervention from the Converter which alters the output (e.g. reindexing versions to Integer)
* **Info** - Just messages about the progress (e.g. "Section Document Tracking handled successfully")

**Comment by tschmidtb51** [comment]
> @tschmidtb51 would you agree? Do you have an idea for use-case for Errors?

Here is the official answer:

- **Critical**: Converter encountered a case which it can not handle and exits immediately without producing any output, exiting with non-zero code. E.g. unfixable invalid input CVRF
- **Error**: Converter encountered a case which it can not handle, or is not defined clearly in the standard; that state does not produce any output unless the `--force` flag/config option is specified, which produces output that is invalid (use case: convert to JSON, fix the errors manual, e.g. in Secvisogram). Some errors can be "downgraded" to warnings by adding a special flag/config option, e.g. `--fix_current_version_not_in_revision_history`
- **Warning**: Any intervention from the Converter which alters the output (e.g. reindexing versions to Integer); additionally: whatever case the standard defines to produce a warning
- **Info**: Just messages about the progress (e.g. "Section Document Tracking handled successfully")

Was that clear?

**Comment by cgi1** [comment]
This is agreed - Closing it here.

**Comment by sustefil** [comment]
The logging is finally crystal clear after this agreement:

https://github.com/csaf-tools/CVRF-CSAF-Converter/pull/38#discussion_r793714467
