### ISSUE TITLE
Implement the ProductTree group of sections

### ISSUE THREAD

**Issue by sustefil** [csaf-tools/CVRF-CSAF-Converter#26]
Part of EPIC #10

## [CVRF 1.1 view](https://github.com/csaf-tools/CVRF-CSAF-Converter/issues/6#issuecomment-984599492)

![grafik](https://user-images.githubusercontent.com/18695252/149393816-7d0cda0a-f256-447a-9171-22ef793bfcf9.png)

### E.1 Newly introduced elements

* `/product_tree/*/product/product_identification_helper`: Provides at least one method which aids in identifying the product in an asset database. It was introduced to group different ways to identify a product/
* `/product_tree/*/product/product_identification_helper/hashes`: Contains a list of cryptographic hashes usable to identify files.
* `/product_tree/*/product/product_identification_helper/purl`: The package URL (purl) attribute refers to a method for reliably identifying and locating software packages external to this specification.
* `/product_tree/*/product/product_identification_helper/sbom_urls`: Contains a list of URLs where SBOMs for this product can be retrieved.
* `/product_tree/*/product/product_identification_helper/serial_numbers`: Contains a list of parts, or full serial numbers.
* `/product_tree/*/product/product_identification_helper/skus`: Contains a list of parts, or full stock keeping units.
* `/product_tree/*/product/product_identification_helper/x_generic_uris`: Contains a list of identifiers which are either vendor-specific or derived from a standard not yet supported.

### E.2 Changed elements

[Around 130 element changes are documented](https://github.com/tschmidtb51/csaf/edit/csaf-2.0-what-is-new-table/notes/whats-new-csaf-v2.0-cn01.md) --> `/cvrf:cvrfdoc/prod:ProductTree` 

## Field definitions

[3.2.2 Product Tree Property](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/prose/csaf-v2-editor-draft.md#322-product-tree-property)

`/product_tree/relationships[]`: If more than one `prod:FullProductName` instance is given, the CVRF CSAF converter converts the first one into the full_product_name. In addition, the converter outputs a warning that information might be lost during conversion of product relationships. [quoted here](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html#915-conformance-clause-5-cvrf-csaf-converter)

**Comment by cgi1** [comment]
Added special case from [9.1.5 Conformance Clause 5: CVRF CSAF converter](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html#915-conformance-clause-5-cvrf-csaf-converter)

**Comment by cgi1** [comment]
added newly/changed elements from [1.2 -> 2.0 spec](https://github.com/tschmidtb51/csaf/blob/csaf-2.0-what-is-new-table/notes/whats-new-csaf-v2.0-cn01.md#e4-mapped-elements).
