### ISSUE TITLE
Define output name based on CSAF standard

### ISSUE THREAD

**Issue by cgi1** [csaf-tools/CVRF-CSAF-Converter#42]
- Output file name is based on DocumentTrackingId
- Change CLI option for for output filename into `output-dir`

[Check CSAF standard 5.1](https://docs.oasis-open.org/csaf/csaf/v2.0/csd01/csaf-v2.0-csd01.html#51-filename)

**Comment by tschmidtb51** [comment]
Additional comment: If one of the [mandatory tests](https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html#61-mandatory-tests) fails, please append `_invalid` to the filename:
`cisco-sa-20190513-secureboot.json` would become `cisco-sa-20190513-secureboot_invalid.json`

**Comment by cgi1** [comment]
Will be implemented until 21.02.2022.

**Comment by cgi1** [comment]
Have been implemented as part of #62 👍
