### ISSUE TITLE
Validate CSAF output against CSAF schema

### ISSUE THREAD

**Issue by sustefil** [csaf-tools/CVRF-CSAF-Converter#45]
A "first-level" validation for validating the output is verifying that it's compliant with the CSAF JSON schema.

The validation comes right before saving the output to a file, and:

Valid -> logging INFO
Invalid -> logging ERROR (writing into a file depends on the `--force` option, this will be implemented when handling `--force` in general)

**Comment by cgi1** [comment]
Please use strict schema instead: https://github.com/secvisogram/secvisogram/blob/main/app/lib/shared/Core/csaf_2.0_strict.json

Otherwise invalid variable names are not throwing a error. strict version is also used in secvisogram.
