### ISSUE TITLE
Integrate turvallisuusneuvonta

### ISSUE THREAD

**Issue by sustefil** [csaf-tools/CVRF-CSAF-Converter#55]
As discussed here:

https://github.com/csaf-tools/CVRF-CSAF-Converter/issues/14#issuecomment-1039012590

Integrate the mandatory tests into cvrf2csaf.py:

https://github.com/sthagen/turvallisuusneuvonta

**Comment by tschmidtb51** [comment]
@sthagen Thanks for the great work!
