### ISSUE TITLE
RegEx validation for CPE not correct

### ISSUE THREAD

**Issue by mfd2007** [csaf-tools/CVRF-CSAF-Converter#57]
A valid CPE, according to CPE Naming Format 2.3, can't be used in a CVRF-Document. Regex is to strict / not correct.

[Attribute ]()CPE

The (Common Platform Enumeration) CPE attribute refers to a method for naming platforms external to CSAF CVRF.

« The CPE attribute if present MUST have a value, that is a valid cpe-lang:namePattern as defined in the external specification [[CPE23_N](http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-cs01.html#refCPE23_N)] and related schemas. » [CSAF-5.1.2-2]

Example CPE: [`cpe:2.3:a:gemalto:sentinel_ldk_rte:3.0:*:*:*:*:*:*:*`](https://nvd.nist.gov/products/cpe/detail/817005?namingFormat=2.3&orderBy=CPEURI&keyword=siemens&status=FINAL)

Log: 
2022-02-17 08:56:31,011 - utils - CRITICAL - Input document not valid: Element '{http://docs.oasis-open.org/csaf/ns/csaf-cvrf/v1.2/prod}FullProductName', attribute 'CPE': [facet 'pattern'] The value `'cpe:2.3:a:gemalto:sentinel_ldk_rte:3.0:*:*:*:*:*:*:*'` is not accepted by the pattern `'[c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6}'`. (<string>, line 0).

**Comment by tschmidtb51** [comment]
An there is another point, where the spec differs from the schema. :angry: There is no easy way to fix this other than output a warning for that specific error and ignore it.

**Comment by sustefil** [comment]
Hmm, how about creating an optional flag `--skip-input-validation` with description: `Skips the XSD validation of the input CVRF file. WARNING: This is an experimental feature and can lead to undefined behavior of the conversion`.

Seems more straightforward to me than creating some workarounds around the specific corner cases.

The converter now relies on a valid input (e.g. exceptions might be thrown for missing mandatory input elements)

**Comment by tschmidtb51** [comment]
I'm not a fan of that solution. The problem is: The spec and the schema differ and therefore, `--skip-input-validation` would have to be used all the time (or at least the bigger part of it). This results in a much bigger attack surface and more complex code afterwards as we can't rely on elements which are mandatory.
IMHO, we have no other option here as handle those as separate cases - ignoring the errors they throw.

**Comment by cgi1** [comment]
@sthagen & @tschmidtb51: Isn't fixing the [CVRF 1.2 schemata](https://github.com/csaf-tools/CVRF-CSAF-Converter/blob/main/cvrf2csaf/cvrf2csaf.py#L34) specification correct here? 

I mean - A specification is __by design__ the truth. 
The schemata __must be__ the __consistent interpretation__ of the specification.

As the CVRF 1.2 Schemata [differs from the original specification](https://github.com/csaf-tools/CVRF-CSAF-Converter/issues/57#issuecomment-1042840002), it become close to impossible for content-providers and (in this example) converters to check against the standard.

**Comment by pixelkunst-net** [comment]
> A valid CPE, according to CPE Naming Format 2.3, can't be used in a CVRF-Document. Regex is to strict / not correct.
> The (Common Platform Enumeration) CPE attribute refers to a method for naming platforms external to CSAF CVRF.
> Example CPE: [`cpe:2.3:a:gemalto:sentinel_ldk_rte:3.0:*:*:*:*:*:*:*`](https://nvd.nist.gov/products/cpe/detail/817005?namingFormat=2.3&orderBy=CPEURI&keyword=siemens&status=FINAL)
`'cpe:2.3:a:gemalto:sentinel_ldk_rte:3.0:*:*:*:*:*:*:*'` is not accepted by the pattern `'[c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6}'`. (, line 0).

The regex above looks to me like validating CPE 2.2, not 2.3. 

Maybe we use the regex from Secvisogram (our reference), which accepts both CPE versions (2.2 and 2.3):

![image](https://user-images.githubusercontent.com/68826866/154635748-53f187d5-e6df-4205-9f51-716da57613c2.png)

![image](https://user-images.githubusercontent.com/68826866/154636176-9354ee99-8eda-4211-ba20-569358249b3b.png)

**Comment by tschmidtb51** [comment]
In principle, this is possible. A modification to the original schemes should be documented in the README.md.

**Comment by cgi1** [comment]
first expression: dont really like changing the input schema
maybe it is easier to build an expception around the wrong regex in the schema and output a warning.

**Comment by cgi1** [comment]
exception has been implemented in #68 #69.
