### ISSUE TITLE
Nit: Unused import in document leaf element handler

### ISSUE THREAD

**Issue by sthagen** [csaf-tools/CVRF-CSAF-Converter#75]
Suggest for spring cleaning to handle the finding
flake8 &rightarrow; [`cvrf2csaf/section_handlers/document_leaf_elements.py:1:1: F401 'logging' imported but unused`](https://github.com/grantmcconnaughey/Flake8Rules/blob/master/_rules/F401.md)

Just remove line 1 stating:
> `import logging`

**Comment by cgi1** [comment]
@tschmidtb51: dont really understand in this issue, that removing an unused libary from the imports is part of critical acceptance. Also observing addition of `acceptance` where the usage is questionable.

**Comment by sthagen** [comment]
Not being part of the process, but in my experience the inclusion into acceptance depends on what is expected of code security as well as quality. Here, unused code has been removed. I know of companies where you only ship when all unused code is gone for good.

**Comment by tschmidtb51** [comment]
@cgi1: I just want to point out that subsection "Code Qualität" (5.1.3, page 14) of your tender mentions `flake8` as one of the best practices...
