### ISSUE TITLE
Deprecation: Fix the invalid backslash-character pairs

### ISSUE THREAD

**Issue by sthagen** [csaf-tools/CVRF-CSAF-Converter#77]
Suggest for spring cleaning to handle the finding
flake8 &rightarrow; 
    [`cvrf2csaf/cvrf2csaf.py:40:92: W605 invalid escape sequence '\.'`](https://github.com/grantmcconnaughey/Flake8Rules/blob/master/_rules/W605.md)
    [`cvrf2csaf/cvrf2csaf.py:40:95: W605 invalid escape sequence '\-'`](https://github.com/grantmcconnaughey/Flake8Rules/blob/master/_rules/W605.md)
    [`cvrf2csaf/cvrf2csaf.py:73:35: W605 invalid escape sequence '\.'`](https://github.com/grantmcconnaughey/Flake8Rules/blob/master/_rules/W605.md)
    [`cvrf2csaf/section_handlers/vulnerability.py:162:35: W605 invalid escape sequence '\.'`](https://github.com/grantmcconnaughey/Flake8Rules/blob/master/_rules/W605.md)
    [`cvrf2csaf/section_handlers/vulnerability.py:170:29: W605 invalid escape sequence '\.'`](https://github.com/grantmcconnaughey/Flake8Rules/blob/master/_rules/W605.md)

Just prefixing the string literals with an `r` should work

Adding a second backslash `\` &rightarrow; `\\` (making the combination a valid backslash escape) works also, but who would want to do that :wink: ...?

**Comment by tschmidtb51** [comment]
@sthagen Someone did that in the JSON schema :wink: But I agree with raw strings...
