### ISSUE TITLE
Transfer PyPI project

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-tools/CVRF-CSAF-Converter#87]
The package is currently on [PyPI](https://pypi.org/project/cvrf2csaf/). The ownership should be transferred or new maintainers from the project should be added.

**Comment by sustefil** [comment]
Hi @tschmidtb51, can you provide the specific metadata that we should change in the PyPI package?

**Comment by sustefil** [comment]
Owner invitation for the project sent to:

https://pypi.org/user/tschmidtb51/

**Comment by tschmidtb51** [comment]
Thanks. Accepted. I'll remove the label acceptance but keep the ticket open until `1.0.0` is public.

**Comment by tschmidtb51** [comment]
Clean-up: Version was released.
