### ISSUE TITLE
Implement converter for first recursive XML section: DocumentTracking

### ISSUE THREAD

**Issue by cgi1** [csaf-tools/CVRF-CSAF-Converter#9]
As part of #3, we already integrated a 1-to-1 mapping between a flat XML element (`DocumentPublisher`). 

Here, we would go into the first recursive conversion: DocumentTracking

This will provide us the code basis to go over other recursive sections in the further project one by one.

**Comment by zpevma** [comment]
The code now uses lxml's objectify. First implementation of DocumentTracking handler class can be found [here](https://github.com/csaf-tools/CVRF-CSAF-Converter/tree/document_tracking_test).

Still need to implement this requirement: 


> type /$defs/version_t: If any element doesn't match the semantic versioning, replace the all elements of type /$defs/version_t with the corresponding integer version. For that, CVRF CSAF converter sorts the items of /document/tracking/revision_history by number ascending according to the rules of CVRF. Then, it replaces the value of number with the index number in the array (starting with 1). The value of /document/tracking/version is replaced by value of number of the corresponding revision item. The match must be calculated by the original values used in the CVRF document.

**Comment by cgi1** [comment]
huh... pretty extensive code already!

The [general section handler](https://github.com/csaf-tools/CVRF-CSAF-Converter/blob/document_tracking_test/src/common/common.py) as a basis looks good.

Then [the first recursive implementation here](https://github.com/csaf-tools/CVRF-CSAF-Converter/blob/document_tracking_test/src/section_handlers/document_tracking.py) provides a good guideline for the next structures.

After finishing the `/$defs/version_t`, @tschmidtb51 could take a look in between, as we only have the next meeting in January. 

Thank you @sustefil and @zpevma!

**Comment by cgi1** [comment]
Happy new year everyone! 🥳 

@zpevma and @sustefil, as a last step, finished the integration of `version_t` [here](https://github.com/csaf-tools/CVRF-CSAF-Converter/pull/21/files#diff-792c6affc308041080a0d015ac1468028f979cd4ce6775ebda476c97e2f363a3R51) - with comments from @sthagen (thanks for the collaboration!).

@tschmidtb51 / @pixelkunst-net: Lets check this pull request tomorrow as part of our weekly call (#21).
