### ISSUE TITLE
Clarify location of config file

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-tools/CVRF-CSAF-Converter#93]
[Originally](https://github.com/csaf-tools/CVRF-CSAF-Converter/issues/27#issuecomment-1013519825), we discussed to have a command line option (e.g. `-c`) to provide a config file. That was not implemented.

However, it is currently unclear where the config file is when it is installed
a) directly from GitHub (in the venv as described)
b) via pip

Please clarify that in the README.

**Comment by sustefil** [comment]
Hi @tschmidtb51,

It's already in the readme, both a) and b) install the config file inside the site-package

https://github.com/csaf-tools/CVRF-CSAF-Converter/blob/main/README.md#config

**Comment by tschmidtb51** [comment]
@sustefil 

Sorry, I might be missing something here:
1. What does the `...` refer to?
2. When cloned from GitHub and installed in the `venv`: Where is the folder `site-packages/`? Maybe having a path that starts with `$ROOT_DIR` could help...
3. When installing from PyPI: Where is the folder `site-packages/`?

**Comment by tschmidtb51** [comment]
BTW: I guess "Convertor" in the last sentence of the linked section in the Readme should actually be a "Converter"...

**Comment by sustefil** [comment]
Fixed the readme to be more explicit

https://github.com/csaf-tools/CVRF-CSAF-Converter/blob/main/README.md#config

**Comment by sustefil** [comment]
@tschmidtb51 can be closed?

**Comment by tschmidtb51** [comment]
@sustefil: Yes. Please do not forget to mention issue numbers in commits. It makes the life and reviewing much easier. Thanks!
