### ISSUE TITLE
Wrong version when installing from source

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-tools/CVRF-CSAF-Converter#94]
When installing from GitHub, the `cvrf2csaf -v` lists the version `1.0.0rc1`. That is incorrect as it should be `git describe` states (e.g. `1.0.0-rc2-2-g262dcd0`).

**Comment by sustefil** [comment]
Well, how do you think this could be implemented? 

Afaik this is a standard approach, that you bump the version manually before creating a tagged package/release.

Tried with multiple libraries (requests, turvallisuusneuvonta, PyMISP), if you install them from source, you get the latest tagged version (using `<package>.__version__`), no matter which revision/commit you have checkout.

**Comment by tschmidtb51** [comment]
It might be that I'm completely wrong here, but why don't we use `git decribe` within `__init__.py`? If we can't determine that automatically, why is it within `__init__.py` and not `setup.cfg`?

@sthagen: Any opinions?

**Comment by sthagen** [comment]
In compiled languages we normally inject a `-D`  value per the build tool chain as the source itself rarely knows what marketing or customers wnat to tbe written there.

With python "installing from source" is maybe a bit vague.

> Personally, I would use in `pyproject.toml` the "Blessed" dependency `setuptools-scm` and have that drive the version variable content per derivitaion from version value in `setup.cfg` and git status (latest tag going backlwards in current branch) and exposing if that version is dirty and in how many commits forward. I played around it in a toy project [`piipaa` at `https://github.com/sthagen/piipaa`]( https://github.com/sthagen/piipaa/) and that approach seems to work nicely (given the plain intended version when (1) tag, (2) current commit, and (3) `setup.cfg` declared version value match and amended versions else (also adhering to whatever pplanet python packaging suggests as version expressions ...

Having provided my opinion, I think one can always change later how to manage versions (after the initial acceptance) and repeating: "installing from source" may be too broad a use case to solve perfectly. Imagine a user downloading the source archive and not having git installed on their machine - that should work, right? In that case one can only use python tools (no `git describe`)

**Comment by tschmidtb51** [comment]
When I wrote "installing from source" I meant through the process described in the Readme - which obviously has a `.git`. However, you are right that doesn't necessarily need to be the case.

@sustefil: [`setuptools-scm`](https://pypi.org/project/setuptools-scm/) sounds reasonable for the use cases which need to be covered for acceptance and does not rely on an installed `git`. Do that answer your question regarding the implementation?

**Comment by sustefil** [comment]
> It might be that I'm completely wrong here, but why don't we use `git decribe` within `__init__.py`? If we can't determine that automatically, why is it within `__init__.py` and not `setup.cfg`?
> 
> @sthagen: Any opinions?

You cannot put `git describe` inside __init__.py. The __init__.py content is executed when the package is imported, if there is something like `subprocess.call('git describe')`, then it works only if your current working directory is inside that git repository (and you have git installed ofc), and that doesn't make sense.

**Comment by sustefil** [comment]
Ok, seems to be working as expected, I did a test on my machine, see the log:

[setuptools-scm-test.txt](https://github.com/csaf-tools/CVRF-CSAF-Converter/files/8481491/setuptools-scm-test.txt)

The file `_version.py` is generated upon `pip install (-e) .`, so before creating an sdist for PyPI, you have to run `pip install (-e) .`

Changes are in the Pull request #104
