### ISSUE TITLE
Correct implementation to conform CSD02

### ISSUE THREAD

**Issue by tschmidtb51** [csaf-tools/CVRF-CSAF-Converter#98]
Here is a short list:
- [ ] make `ids` an array
- [ ] check on `/document/tracking/id` and remove whitespace
- [ ] add `legacy_number`

**Comment by ir-dev** [comment]
> Here is a short list:
> 
> - [ ] make `ids` an array
> 
> - [ ] check on `/document/tracking/id` and remove whitespace
> 
> - [ ] add `legacy_number`

There is an essential one missing:
[ ] remediations fallback product ids from `product_status`
